### ISSUE TITLE
It seems that the website http://snapp.citilab.eu/ is not currently working.

### ISSUE THREAD

**Issue by ConcernedToast** [Rydion/Snapp#1]
When I click on the link http://snapp.citilab.eu/ from snap!'s website, I get the error "This site cannot be reached. snap.citilab.eu refused to connect"
Here is an image of the error that I receive:

<img width="849" alt="connection refused" src="https://cloud.githubusercontent.com/assets/19367342/15271443/ba680dac-1a17-11e6-8d38-25490eb720b7.PNG">

Is there anything that I am doing wrong?

**Comment by Rydion** [comment]
The server was down, should be back up again.
