### ISSUE TITLE
SVG graphics not working correctly

### ISSUE THREAD

**Issue by nickedens** [Rydion/Snapp#13]
When created with Snap! the game looks like this
![capture2](https://cloud.githubusercontent.com/assets/22965711/21988741/5541e3cc-dbd6-11e6-8539-2dec9740d5ba.PNG)

However after I compile it with Snapp! we lose most (not all) of the graphics. For some reason the wall SVG still shows but everything else is gone.

![capture](https://cloud.githubusercontent.com/assets/22965711/21988775/72195e26-dbd6-11e6-84d8-3be66aa6af56.PNG)

**Comment by Rydion** [comment]
Hi,

I'll look into it. Can I have access to the project you used to reproduce
the bug?

**Comment by nickedens** [comment]
Attached is the zip file. We use a self hosted version of Snap! to teach kids programming in our non profit. We were just going to start letting the kids take their snap programs into executable but I wanted to try one before we let them. Hoping its an easy fix. Thank you so much for looking into it for us!
 
[Flappy Bird (16).zip](https://github.com/Rydion/Snapp/files/709147/Flappy.Bird.16.zip)

**Comment by Rydion** [comment]
Hi, the problem should be solved. I've already pushed the changes. Could you try once again to generate the executable and tell me if it's working for you too?

**Comment by nickedens** [comment]
The graphics all show now! I am getting some really strange gapping behavior though but I'll look into that on my side and if it seems to be a real issue with Snapp then I will post another bug with information. 

Thank you so much for your help!

**Comment by nickedens** [comment]
I did just confirm this is an issue with Snap! not with Snapp!

Just wanted to let you know.

**Comment by Rydion** [comment]
Hi, thank you for letting me know. I hope you can get it fixed soon, the
project was pretty cool!
