### ISSUE TITLE
Looking to host

### ISSUE THREAD

**Issue by nickedens** [Rydion/Snapp#16]
Hello! I run a non profit that teaches kids to code (http://hackbg.org). We currently host our own custom version of Snap!

I would really love to integrate a self hosted solution using your program. I was looking around for some sort of Read Me and took a look at the webpage that you do the converting on and I am at a bit of a loss. Is there any way you could do a quick example implementation for this? I realize you are probably extremely busy but any help or guidance would be appreciated for sure!

**Comment by Rydion** [comment]
Hi @nickedens,

after being absent from the project for a while I've finally found time to work on it again. I'll be pushing a new version with several improvements over the next few days. These improvements will also include documentation which in turn will contain a guide on how to self-host Snapp.

I'd like to ask you to wait 'til this is all done. After that, if you were to need any extra help with the process of self-hosting I'll be glad to help.

**Comment by nickedens** [comment]
@Rydion that sounds great. I do appreciate it! Can't wait to see the new version!

**Comment by Rydion** [comment]
Hi @nickedens,

just wanted you to know that the new version is up.

Check out the new [wiki](https://github.com/Rydion/Snapp/wiki). There's still some information missing, but it should explain everything you need to self-host your own Snapp version. If there's something that's not entirely clear just let me know and I can give you a hand, and rewrite the documentation to make it more understandable.

Cheers.
