### ISSUE TITLE
Executable don't seem to work in Raspbian on a Raspberry Pi 3.

### ISSUE THREAD

**Issue by DarinM1967** [Rydion/Snapp#17]
HW: Raspberry Pi 3
OS: Raspbian version: 12.7

Tried compiling Space Invaders.snap, which appeared to compile (Linux 32 bit), but when I try to run Space Invaders.desktop, launcher.sh, or Space Invaders nothing happens.  I have tried running when from UI and from Terminal window.  In the terminal window the cursor appears to be frozen in the upper left corner of the Terminal Window. Tried changing the name of the binary from "Space Invaders" to "Space-Invaders", but didn't help.

**Comment by bromagosa** [comment]
Nope, it will not work in a Raspberry Pi, as it's an ARM-based board, and there is no official nwjs.io build for that processor architecture.

However, there's an unofficial port that people report to be working: https://github.com/jalbam/nwjs_rpi

What do you think @Rydion, would it be very hard to add yet another platform to the mix?

**Comment by Rydion** [comment]
Thank you @bromagosa for the quick reply.

As for Snapp's compatibility with Raspberry Pi. I'm sorry but I will not include it unless NW.js releases an official compatible pre-built binary.
