### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by buttle** [Rydion/Snapp#18]
Hi,
We're building a type of old-school arcade machine to play snap! projects and Snapp is just what we're looking for. Thank you so much.

We'd like to run the projects in fullscreen. Is that possible?

Thanks.

**Comment by Rydion** [comment]
Hi,
If you are on Windows, it's possible by pressing the F11 key.
On Linux and Mac it's currently not possible... Due to nobody asking for
it! It should be easy to implement if you need it.
