### ISSUE TITLE
multiple process executing

### ISSUE THREAD

**Issue by buttle** [Rydion/Snapp#19]
Hi,
Looking at the processes running on the machine we see this.

`user      4612     1 18 00:13 tty1     00:00:12 /home/user/arcade/projects/snake.snapp/snake
user      4614  4612  0 00:13 tty1     00:00:00 /home/user/arcade/projects/snake.snapp/snake --type=zygote --no-sandbox --enable-crash-reporter
user      4635  4614 99 00:13 tty1     00:01:04 /home/user/arcade/projects/snake.snapp/snake --type=zygote --no-sandbox --enable-crash-reporter
user      4637  4614  0 00:13 tty1     00:00:00 /home/user/arcade/projects/snake.snapp/snake --type=zygote --no-sandbox --enable-crash-reporter`

Why are there so many? and, What do the arguments mean?

Thanks.

**Comment by Rydion** [comment]
Hi, under the hood Snapp uses [NW.js](https://nwjs.io/). So when you launch a Snapp project, you really are starting up NW.js which then loads the project.

I'm not familiar with those flags either, they seem to be some defaults that NW.js uses and correspond to chromium.  Maybe [this link](http://peter.sh/experiments/chromium-command-line-switches/) can give you more information.

As for why there's more than one process I don't really know, maybe NW.js needs it, or you started the project more than once.
