### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by Yiaq** [Rydion/Snapp#2]
[Same ERR_CONNECTION_REFUSED error again](https://github.com/Rydion/Snapp/issues/1).  This came after I used the site multiple times in a row, so I might have crashed the server.  Sorry :( .  I was using it so much because [this project ](http://snap.berkeley.edu/snapsource/snap.html#present:Username=Yiaq&ProjectName=1-Player%20Guns%20and%20Lasers)wan't compiling correctly.

**Comment by Yiaq** [comment]
Come to think of it, would having Node.js without the correct modules (I only did step one of the installation) cause a project to compile incompletely?  That might be the answer to the second part of my issue.

**Comment by Rydion** [comment]
Hi, don't worry, massive use shouldn't crash the app, although it was down for some reason. I don't have much control over the server but I'll try to get in touch with some people that may get these issues sorted out.

As for the project not compiling, I'm currently working on an update to get Snapp! up to date with Snap!, that should hopefully solve any problem you are facing. If not just let me know one it rolls out and I'll see what I can do.

**Comment by Yiaq** [comment]
Ok.  Thanks!

**Comment by Rydion** [comment]
Hi, just to let you know I just updated Snapp! and now your project works flawlessly! If you find any other projects that don't work as expected just let me know.
