### ISSUE TITLE
Snapp! uses an old version of Snap!, causing new projects to be incompatible.

### ISSUE THREAD

**Issue by maxrrs** [Rydion/Snapp#21]
Loading a new project will cause an error message, and fail to load as the the version of Snap! on the Berkeley website differs greatly from the one on the Snapp! website. Specifically, Snapp! uses Snap! 4.010.2, while the most recent is 4.1.2.7.

![image](https://user-images.githubusercontent.com/14227407/41500655-8b796a02-715b-11e8-92d5-94ad8e84b188.png)

**Comment by Rydion** [comment]
Hi @maxrrs,

thank you for bringing this to my attention. I know that Snapp is lagging behind quite a bit, I usually try to avoid updating as my ability to test changes on linux and mac is limited (nonexistent). But if it's causing projects to fail in this way I'll try my best to update the Snap version asap.

Expect an update during next week.

**Comment by Rydion** [comment]
I've created a new version of Snapp that uses an up to date version of Snap. If you were self hosting please deploy the new version, if not I've also updated the version at [http://snapp.citilab.eu/](http://http://snapp.citilab.eu/).

Please let me know if everything works for you now or if you encounter any other issues.

**Comment by maxrrs** [comment]
Thanks for your replies. It fills me with joy to know that wonderful content creators such as yourself are still paying attention to older projects such as this. For anyone reading this in future and this has become an issue again, you can try to work around the issue until it gets updated by doing the following (Windows):

1- Download the Snap source from the Berkeley website (https://snap.berkeley.edu/snapsource/snap.zip)
2- Open the .exe file created by Snapp using 7-Zip or a similar program, and replace the present files with the ones included in the source .zip.

I haven't tested this myself, but it seems plausible.

**Comment by Rydion** [comment]
Sadly, although the process is reasonable, that approach will not quite work. Snapp uses a modified version of the Snap source code found [here](https://github.com/Rydion/Snap-4-Snapp). I maintain this version and updating that code is usually the hardest part as there may be breaking changes (that break Snapp) from one Snap version to the next.
