### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by Rydion** [Rydion/Snapp#24]
@bromagosa Hola, no sé si encara estàs amb el Citilab, però potser pots indicar-me amb qui he de parlar. Aparentment snapp.citilab.eu apunta a una màquina diferent i ja no hi tinc accés. Ara mateix la versió que hi ha té un bug important a mac i m'interessaria fer deploy de la nova versió.

**Comment by bromagosa** [comment]
Hola! No estic al Citilab però et passo el contacte. M'escrius a bernat arroba romagosa punt work i en parlem?

Salut!
