### ISSUE TITLE
Mobile Support and a library

### ISSUE THREAD

**Issue by TopGamerPro16** [Rydion/Snapp#39]
why doesn't Snapp! have mobile support? (if you could implement this, both iPA and APK would be requested please.) if you would like this too, and it is possible, please add this. it would unlock many new things. 
one note: if you somehow can, make a (on its own) useless library, but, that when converted, does what is said on its label.

eg: [send notification []]
i only need this for a snap server i am making.

**Comment by TopGamerPro16** [comment]
sorry if i get partially off topic...

**Comment by adrian-hintze** [comment]
Snapp doesn't have mobile support because the platform that it uses in the background (NW.js) doesn't have one either. Even if it was available I doubt I would have the hardware to test it.

Not sure what a "useless library" is? Mind elaborating?

**Comment by Jfhseh** [comment]
> sorry if i get partially off topic...

I think I find the solution to anti-cheat, if you export a project as exe using snapp!, with your cloud vars, it'll work and I don't think people can access the code when it is exported to an exe file.

**Comment by Jfhseh** [comment]
> Snapp doesn't have mobile support because the platform that it uses in the background (NW.js) doesn't have one either. Even if it was available I doubt I would have the hardware to test it.
> 
> Not sure what a "useless library" is? Mind elaborating?

Rqndom question： how do you earn money from this to keep the server open？

**Comment by TopGamerPro16** [comment]
i dont. i just use a home computer, and then randomly came to think snapp supports netsblox :P lol!

________________________________

This email and any files transmitted with it are the property of the Brownsville Independent School District, are confidential, and are intended solely for the use of the individual or entity to whom this email is addressed. If you are not one of the named recipient(s) or otherwise have reason to believe that you have received this message in error, please notify the sender and delete this message immediately from your computer. Any other use, retention, dissemination, forwarding, printing, or copying of this email is strictly prohibited.

BISD does not discriminate on the basis of race, color, national origin, gender, religion, age, disability or genetic information in employment or provision of services, programs or activities.

BISD no discrimina a base de raza, color, origen nacional, género, religión, edad, discapacidad o información genética en el empleo o en la provisión de servicios, programas o actividades.

**Comment by TopGamerPro16** [comment]
Re:to known as "coconut104"...

i dont. and i cant beleive i thought this supported netsblox at the time.
i use a home computer.

and to the first, i honestly thought there was a file that shows the xml data.

**Comment by TopGamerPro16** [comment]
and to adrian, ok, but wat i meant was things exes' can do, outside of their window. like as i said, senging notifications/ for windows 8.1-, the little bubble on the bottom. also, maybe the ability to use vbs?

like what i now have, 
the "decsoft html compiler". it has some features too, that also allow me to close its window................................................................................................................................................................ without the uselessness of window.close() that temporarily worked. it has the ability to detect when it is being closed, but can give the "are you sre you want to leave this page?" a customization.

**Comment by adrian-hintze** [comment]
@Jfhseh,
No, I work on Snapp during my free time and the public server is ran at a loss. Everyone is free to fork, modify, and run their own version as well (which may be potentially more stable).

@TopGamerPro16 
The goal of Snapp is to run your Snap project as an independent application. No additional functionality will be added outside of the sandboxed environment that Snap provides.
