### ISSUE TITLE
License of exported executables / Linux ARM

### ISSUE THREAD

**Issue by MickaelH974** [Rydion/Snapp#4]
Hi, 

Can you tell us more about licenses of exported executables please?

Is there any way to export a project for an ARM linux board like Raspberry pi?

Thanks.

**Comment by Rydion** [comment]
Hi,
any executable created by Snapp! depends on 3 things, Snap!, [NW.js](http://nwjs.io/) and the user's project.

Snap! is distributed under the terms of GPLv3 and NW.js under several, like the MIT license. Snapp! itself is distributed under GPLv3 as well. I'm not the most knowledgeable person when it comes to licensing, but I think that as long as you bundle all the necessary licenses with the executables and the project is yours you should be fine doing whatever with it.

As for ARM support I completely depend on the NW.js team building for and supporting that platform. Which means it is not supported atm (also I don't really have the means to test it properly), but if you know someone who would like to take the task into their own hands please let me know!
