### ISSUE TITLE
Netsblox support

### ISSUE THREAD

**Issue by TopGamerPro16** [Rydion/Snapp#42]
@adrian-hintze,
will you be able to add support for NetsBlox formatted XMLs so that i can communicate with others of the ouutput executable?
ik it is not snap, but it adds a little more function.

**Comment by TopGamerPro16** [comment]
go to Netsblox.org if you dont know what it is, and editor.netsblox.org to try out the extra features to be addid if you do.

**Comment by adrian-hintze** [comment]
Hi @TopGamerPro16,

Any functionality not strictly related to Snap is not in scope.

I'm hoping to rewrite the Wiki this year with up-to-date info on how to deploy/build the project so a fork to add the needed functionality should be fairly straightforward.

Regards,
Adrian
