### ISSUE TITLE
Can't access server.

### ISSUE THREAD

**Issue by brendaraymondcr** [Rydion/Snapp#5]
Hi, I would love to use your tool but I haven't been able to access the server yesterday or today.
Receiving message:   This site can’t be reached

snapp.citilab.eu refused to connect.
Search Google for snapp citilab eu
ERR_CONNECTION_REFUSED

**Comment by Rydion** [comment]
Hi, thank you for letting me know.
I don't have access to the server to fix it as it is provided by a third party (Citilab), but I have contacted them already to see if they can do something about it.

Hopefully it will be up and running again by tomorrow. Once it's online again I'll let you know.

**Comment by bromagosa** [comment]
Hi there, I've contacted the IT person in the Citilab, see if he knows something about this. Hopefully he won't be on holidays yet... :worried:

**Comment by Rydion** [comment]
Everything's up and running again.
